name: sbpos_v2
description: A new Flutter project.
version: 1.0.0+1
publish_to: none
environment:
  sdk: '>=3.4.1 <4.0.0'
dependencies:
  core:
    path: core
  dashboard:
    path: features/dashboard
  flutter:
    sdk: flutter
  landing_page_menu:
    path: features/landing_page_menu
  mode:
    path: features/mode
  outlet:
    path: features/outlet
  product:
    path: features/product
  setting:
    path: features/setting
  transaction:
    path: features/transaction
  cupertino_icons: ^1.0.8
  dotted_border: ^2.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  sqflite_common_ffi: ^2.3.3
  integration_test:
    sdk: flutter
  network_image_mock: ^2.1.1
flutter:
  uses-material-design: true
  assets:
    - .env.local
    - .env.prod
    - assets/images/
