name: product
description: A new Flutter package project.
version: 0.0.1
publish_to: none
environment:
  sdk: '>=3.4.1 <4.0.0'
  flutter: '>=1.17.0'
dependencies:
  core:
    path: ../../core
  flutter:
    sdk: flutter
  landing_page_menu:
    path: ../landing_page_menu
  mode:
    path: ../mode
  outlet:
    path: ../outlet
  transaction:
    path: ../transaction
  dashboard:
    path: ../dashboard
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
