name: transaction
description: A new Flutter package project.
version: 0.0.1
publish_to: none
environment:
  sdk: '>=3.4.1 <4.0.0'
  flutter: '>=1.17.0'
dependencies:
  core:
    path: ../../core
  flutter:
    sdk: flutter
  landing_page_menu:
    path: ../landing_page_menu
  outlet:
    path: ../outlet
  dashboard:
    path: ../dashboard
  product:
    path: ../product
  setting:
    path: ../setting
  customer:
    path: ../customer
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  sqflite_common_ffi: ^2.3.3
  sqflite_common: ^2.3.0
  intl: ^0.20.2
  dartz: ^0.10.1
  fake_async: ^1.3.0
