name: landing_page_menu
description: A new Flutter package project.
version: 0.0.1
publish_to: none
environment:
  sdk: '>=3.4.1 <4.0.0'
  flutter: '>=1.17.0'
dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../../core
  dashboard:
    path: ../dashboard
  mode:
    path: ../mode
  warehouse:
    path: ../warehouse
  product:
    path: ../product
  setting:
    path: ../setting
  notification:
    path: ../notification
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
