name: core
description: A new Flutter package project.
version: 0.0.1
publish_to: none
environment:
  sdk: '>=3.4.1 <4.0.0'
  flutter: '>=1.17.0'
dependencies:
  flutter:
    sdk: flutter
  go_router: ^15.1.2
  drift: ^2.16.0
  sqflite: ^2.3.3+1
  path_provider: ^2.1.1
  path: ^1.8.3
  dartz: ^0.10.1
  flutter_riverpod: ^2.6.1
  flutter_dotenv: ^6.0.0
  connectivity_plus: ^5.0.2
  intl: ^0.20.2
  http: ^1.2.1
  dashboard:
    path: ../features/dashboard
  landing_page_menu:
    path: ../features/landing_page_menu
  mode:
    path: ../features/mode
  warehouse:
    path: ../features/warehouse
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true  # <-- WAJIB ADA!
